### ISSUE TITLE
Possibly need pointer to active stack in main

### ISSUE THREAD

**Issue by Jxgger13** [armac7/Intend2Read#2]
Might be a good idea to have a pointer variable in main that keeps track of our active stack.
Ex: Node* activeStack;

This way we can use this pointer to access any functions we need. For example, if the user chooses to update the stack, then the case code will just be activeStack = updateActiveStack(choice);. This does not have to be the exact function but we would just have to implement it and it would make the code in main look very clean. 

This would also help any time we needed to delete a stack because activeStack will be already pointing to the node that we want to delete. All we would have to do is check all the edge cases, update the pointers in the linked list, delete activeStack (which would also require us to go in and delete each individual instance of book), and then update activeStack. We could even turn this into a function. For example, if the user chooses to delete the stack, we could call a function we create called deleteStack(activeStack); We are passing in the active stack so the function will know which stack to delete. 

Also, we could do something like getting the name of the active stack by activeStack->stack(ptr to instance of stack)
->getName(); This would be one simple line of code if the user chooses that specific case. 

I'm sure that keeping track of an activeStack pointer will help us in other parts of main as well. Think about it and let me know.

**Comment by armac7** [comment]
This worked almost flawlessly. I went a little overboard when coding tonight (as you can see by the time stamp of 2:03am of this message) and coded almost the whole thing 🫠, and this is the main method I used. You can see the code on iss1 branch. I apologize for going overboard. I kind of just locked in.
